# Generated by Django 4.2.13 on 2024-08-04 18:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('length', models.IntegerField()),
                ('breadth', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('priority', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('length', models.IntegerField()),
                ('breadth', models.IntegerField()),
                ('height', models.IntegerField()),
                ('tare_weight', models.IntegerField()),
                ('gvwr', models.IntegerField()),
                ('axle_weight_ratings', models.JSONField()),
                ('axle_group_weight_ratings', models.JSONField()),
                ('wheel_load_capacity', models.DecimalField(decimal_places=2, max_digits=7)),
                ('occupied', models.JSONField(default=list)),
                ('current_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('center_of_gravity', models.JSONField(default=[0, 0, 0])),
            ],
        ),
    ]
