# Generated by Django 4.2.13 on 2024-08-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_shipper', '0004_package_name_truck_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='allocation',
            field=models.CharField(default='---', max_length=50),
        ),
    ]
