# Generated by Django 4.2.13 on 2024-08-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_shipper', '0006_package_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='stock',
            field=models.IntegerField(default=2),
        ),
    ]
