# Generated by Django 4.2.13 on 2024-08-09 13:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_shipper', '0007_alter_package_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link', models.URLField(default='https://www.google.co.in')),
                ('packages', models.JSONField(default=dict)),
                ('approval_truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_shipper.truck')),
            ],
        ),
    ]
