# Generated by Django 4.2.13 on 2024-08-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_shipper', '0009_alter_approval_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='link',
            field=models.URLField(default='http://swp_visualizer:8081/visualization/8ebb569e-06c3-4156-a9e6-f60ca88bbf3a/'),
        ),
    ]
